# Generated by Django 3.0.2 on 2020-01-26 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='corridas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tempo', models.TimeField(blank=True)),
                ('data_da_corrida', models.DateField()),
                ('sentimento', models.CharField(max_length=10)),
                ('observacoes', models.CharField(max_length=400)),
                ('lancado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
