# Generated by Django 3.0.2 on 2020-01-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0002_auto_20200126_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corridas',
            name='observacoes',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
