# Generated by Django 3.0.2 on 2020-04-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0003_auto_20200126_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corridas',
            name='observacoes',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='corridas',
            name='sentimento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='corridas',
            name='tempo',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
