# Generated by Django 3.0.6 on 2020-05-31 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corridas', '0004_auto_20200403_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.TextField(max_length=100)),
                ('distancia_categoria', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagem_categoria', models.TextField(blank=True, max_length=250, null=True)),
                ('corredor_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
